# Generated by Django 5.1.6 on 2025-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('Nequi', 'Nequi'), ('Bancolombia', 'Bancolombia')], max_length=20),
        ),
    ]
